# Generated by Django 3.1.2 on 2020-11-01 16:58

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('goal', models.TextField()),
                ('placeholder', models.TextField()),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='E:\\Projects/winoutt-django/teams/static/teams/team_images/'), upload_to='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
